/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/Button.vue')['default']
    Checkbox: typeof import('./components/Checkbox.vue')['default']
    FormsTemplate: typeof import('./components/FormsTemplate.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InputText: typeof import('./components/InputText.vue')['default']
    RadioButton: typeof import('./components/RadioButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Selectbox: typeof import('./components/Selectbox.vue')['default']
    Textarea: typeof import('./components/Textarea.vue')['default']
  }
}
